// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL6sD93AzRHceFhJk_sm9cWMamPuJvGSk',
    appId: '1:347085841227:web:9a8f9430f42fc639ad7ece',
    messagingSenderId: '347085841227',
    projectId: 'tapass-2026',
    authDomain: 'tapass-2026.firebaseapp.com',
    storageBucket: 'tapass-2026.firebasestorage.app',
    measurementId: 'G-H4Z2MYQ7S7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX3C57Hd6LBdpOop8VPhHvhBJ2KQ3ERgc',
    appId: '1:347085841227:android:f7b3bb49fcc0a712ad7ece',
    messagingSenderId: '347085841227',
    projectId: 'tapass-2026',
    storageBucket: 'tapass-2026.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_VutzsZAkj-v_B1ijth-HgjHPwpAg5Dc',
    appId: '1:347085841227:ios:d1869e0c407ceedaad7ece',
    messagingSenderId: '347085841227',
    projectId: 'tapass-2026',
    storageBucket: 'tapass-2026.firebasestorage.app',
    iosBundleId: 'com.tapass.tapassapp',
  );
}
